apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp
  labels:
    app: restaurantapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp
  template:
    metadata:
      labels:
        app: restaurantapp
    spec:
      containers:
        - name: restaurantapp
          image: mourad01/restaurant-listing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          # env:
          #   - name: SPRING_DATASOURCE_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: secret
          #         key: postgres-username
          #   - name: SPRING_DATASOURCE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: secret
          #         key: postgres-password
          #   - name: SPRING_DATASOURCE_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: configmap
          #         key: restaurantdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-listing
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: restaurantapp