eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/sami
    username: sami
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect