server:
  port: 9000

spring:
  profiles:
    active: local

  application:
    name: restaurantListing

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect